sudo: true
language: ruby
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.1.15.0
matrix:
    allow_failures:
        - rvm: jruby-9.1.15.0

cache: bundler

install:
    - git config --global user.name "Autoproj on Travis CI"
    - git config --global user.email "autoproj@travis"
    - gem install bundler
    # Some tests expect gems to be present in vendor/bundle
    - bundle install --path vendor/bundle
script:
    - bundle exec rake
    - AUTOPROJ_SKIP_LONG_TESTS=1 bundle exec rake test
