sudo: false
language: ruby
rvm:
  - '2.0'
  - '2.1'
  - '2.2'
  - '2.3.1'
  - 'jruby-9.1.2.0'
matrix:
    allow_failures:
        - rvm: 'jruby-9.1.2.0'
script:
    - bundler exec rake
    - bundler exec rake test
